version: '3'
services:
  jenkins:
    container_name: jenkins-server
    image: jenkins/jenkins:jdk11
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins-tomcat-network
    ports:
      - 8080:8080
  tomcat:
    container_name: tomcat-server
    image: tomcat
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps2
    command: bash -c "mv /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps"
    networks:
      - jenkins-tomcat-network
    depends_on:
      - jenkins
    ports:
      - 8082:8080

networks:
  jenkins-tomcat-network:

volumes:
  jenkins_data:
  tomcat_webapps:
