version: '3'
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins-server
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins-tomcat-network
    ports:
      - 8080:8080
  tomcat:
    image: tomcat
    container_name: 
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps
    networks:
      - jenkins-tomcat-network
    depends_on:
      - jenkins
    ports:
      - 8082:8080

networks:
  jenkins-tomcat-network:

volumes:
  jenkins_data:
  tomcat_webapps:
